node:internal/modules/run_main:123
    triggerUncaughtException(
    ^
Error [TransformError]: Transform failed with 1 error:
C:\Users\jimenez.n\Downloads\Server-v2 (19)\Server-v2\server\routes.ts:2032:94: ERROR: Expected "finally" but found ")"
    at failureErrorWithLog (C:\Users\jimenez.n\Downloads\Server-v2 (19)\Server-v2\node_modules\tsx\node_modules\esbuild\lib\main.js:1476:15)
    at C:\Users\jimenez.n\Downloads\Server-v2 (19)\Server-v2\node_modules\tsx\node_modules\esbuild\lib\main.js:755:50
    at responseCallbacks.<computed> (C:\Users\jimenez.n\Downloads\Server-v2 (19)\Server-v2\node_modules\tsx\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (C:\Users\jimenez.n\Downloads\Server-v2 (19)\Server-v2\node_modules\tsx\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (C:\Users\jimenez.n\Downloads\Server-v2 (19)\Server-v2\node_modules\tsx\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)

Node.js v22.17.0
